apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-hello
spec:
  replicas: 2
  selector:
    matchLabels:
      app: node-hello
  template:
    metadata:
      labels:
        app: node-hello
    spec:
      containers:
      - name: app
        image: elsman2020/node-hello:latest
        ports:
        - containerPort: 3000
        env:
        - name: NEW_RELIC_LICENSE_KEY
          valueFrom:
            secretKeyRef:
              name: newrelic-license-key
              key: licenseKey
        - name: NEW_RELIC_APP_NAME
          value: "helloworld-app"
        resources:
          requests:
            memory: "128Mi"
            cpu: "0.25"
          limits:
            memory: "256Mi"
            cpu: "0.5"
